"""empty message

Revision ID: 55c642aa9f90
Revises: 7b4dc3a28190
Create Date: 2021-05-15 23:33:02.223604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c642aa9f90'
down_revision = '7b4dc3a28190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
