"""empty message

Revision ID: 7b4dc3a28190
Revises: 
Create Date: 2021-05-15 23:30:27.167335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4dc3a28190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('street_addr', sa.String(length=60), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occupied', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=True),
    sa.Column('title_address', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('salt', sa.Integer(), nullable=True),
    sa.Column('fname', sa.String(length=40), nullable=True),
    sa.Column('lname', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('TRN', sa.String(length=12), nullable=True),
    sa.Column('role', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('reservations', 'driver_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('reservations', 'license_plate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('reservations', 'lot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reservations', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('reservations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('reservations', 'lot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'license_plate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('reservations', 'driver_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_table('users')
    op.drop_table('lots')
    # ### end Alembic commands ###
